apiVersion: v1
kind: Service
metadata:
  name: hviewserv
  labels:
   app: hview
spec:
  ports:
  - name: http
    port: 80
    nodePort: 30507
  selector:
    app: hview
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hviewcontainer
  labels:
    app: hview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hview
  template:
    metadata:
      labels:
        app: hview
    spec:
      containers:
      - name: hview
        image: devcoolinc/hipass_graph_reactdocker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred