const Strings = {
    CLAIMS : 'claimsManagement',
    REALTIME_837_CLAIM: 'REALTIME_837_CLAIM',
    REALTIME276 : 'real_time_276',
    REALTIME270 : 'real_time_270',
    EDIT_CLAIM : 'editClaim',
    TRAN_MANAGMENT : 'tranMng',
    FULL_FILE : 'full_file',
    TRAD_MANAGEMENT : 'tradMng',
    ENR_MANAGEMENT : 'enrMng',
    PROC_MANAGEMENT : 'procMng',
    REP_MANAGEMENT : 'repMng',
    ACK_MANAGEMENT : 'ackMng',

    claimsDashboard: 'claimsDashboard',
    tradingPartnerDetails : 'tradingPartnerDetails',
    tradingPartnerConfiguration : 'tradingPartnerConfiguration',
    claimsDashboard_835 : 'claimsDashboard_835',
    claimsDashboard_834 : 'claimsDashboard_834',
    claimsDashboard_834_details : 'claimsDashboard_834_details',
    editConfiguration : 'editConfiguration',
    RealTime276 : 'realTime276',
    RealTime270 : 'realTime270',
    submitClaims : 'submitClaims',
    claimDetails : 'claimDetails',
    claimsAudit : 'claimsAudit',
    claimsError : 'claimsError',
    matchClaims : 'matchClaims',
    researchQueue : 'researchQueue',
    viewEdit : 'viewEdit',
    validation : 'validation',
    fullFile834 : 'fullFile834',
    files_834 : 'files_834',
    transactionSetup : 'transactionSetup',
    companionGuide : 'companionGuide',
    covered : 'covered',
    noncovered : 'noncovered',
    AuditSummary270: 'AuditSummary270',
    ErrorDetails276: 'ErrorDetails276',
    ElilgibilityDetails270: 'elilgibilityDetails270',
    ElilgibilityDetails276: 'claimStatusDetails276',
    elilgibilityErrors270: 'elilgibilityErrors270',
    elilgibilityErrors276: 'elilgibilityErrors276',
    ViewCustomEdits: 'viewCustomEdits',
    UserManagement:'UserManagement',
    UserList:'userList',
    MenuCreate:'userRoleManagement',
    ChangePassword:'changePassword',
    EnrollmentError : 'Enrollment_Error', 
    EnrollmentDetails: 'EnrollmentDetails',
    EnrollmentErrors: 'EnrollmentErrors',
    Outbound_dashboard:'Outbound_dashboard',
    Eligibility_Reconcile_Search:'Eligibility_Reconcile_Search',
    Eligibility_Errors:'Eligibility_Errors',
    EligibilityErrorsDelta :'EligibilityErrorsDelta',
    HistoryEligibilityErrorsDelta: 'HistoryEligibilityErrorsDelta',
    RateCodeDelta: 'RateCodeDelta',
    PlanIntegrationEligibilityErrors: 'PlanIntegrationEligibilityErrors',
    HistoryRateCodeDelta: 'HistoryRateCodeDelta',
    MedicalMonthly_Metrics:'MedicalMonthly_Metrics',
    CustomDBDetails: 'CustomDBDetails',
    EligibilityErrorsDuplicate: 'EligibilityErrorsDuplicate',
    OutboundDetails: 'OutboundDetails',
    FullComparsion_dashboard: 'FullComparsion_dashboard',
    ClaimDetails837: 'ClaimDetails837',
    RealTimeDashboard: 'claimsDashboard',
    ClaimProcessingSummary: 'claimProcessingSummary',
    _277CAResponse: '_277CAResponse',
    // ClaimProcessingSummary: 'claimsAudit',
    Files_837 : 'Files_837',
    MenuManagement: 'MenuManagement',
    TradingPartner:'TradingPartner',
    EncounterDashboard:'EncounterDashboard',
    EncounterDetails:'EncounterDetails',
    claimPayment_835: 'claimPaymentDashboard835',
    healthCare278: 'healthCare278Dashboard',
    serviceDetails278: 'serviceDetails278',
    response_999:'response_999'
}

export default Strings;
